### ISSUE TITLE
后端无法启动

### ISSUE THREAD

**Issue by jj-debug** [Yin-Hongwei/vue-spring-music#247]
mvn spring-boot:run
[INFO] Scanning for projects...
[INFO] Artifact org.springframework.boot:spring-boot-starter-parent:pom:2.6.2 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [maven-default-http-blocker (http://0.0.0.0/, default, releases, blocked), central (https://repo.maven.apache.org/maven2, default, releases)]
---------------------------------------------------
constituent[0]: file:/F:/environment/Maven/apache-maven-3.9.1/conf/logging/
constituent[1]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/aopalliance-1.0.jar
constituent[2]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/commons-cli-1.4.jar
constituent[3]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/commons-codec-1.11.jar
constituent[4]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/commons-lang3-3.8.1.jar
constituent[5]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/failureaccess-1.0.1.jar
constituent[6]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/guava-30.1-jre.jar
constituent[7]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/guice-5.1.0.jar
constituent[8]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/httpclient-4.5.14.jar
constituent[9]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/httpcore-4.4.15.jar
constituent[10]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/jansi-2.4.0.jar
constituent[11]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/javax.annotation-api-1.3.2.jar
constituent[12]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/javax.inject-1.jar
constituent[13]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/jcl-over-slf4j-1.7.36.jar
constituent[14]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-artifact-3.9.1.jar
constituent[15]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-builder-support-3.9.1.jar
constituent[16]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-compat-3.9.1.jar
constituent[17]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-core-3.9.1.jar
constituent[18]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-embedder-3.9.1.jar
constituent[19]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-model-3.9.1.jar
constituent[20]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-model-builder-3.9.1.jar
constituent[21]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-plugin-api-3.9.1.jar
constituent[22]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-repository-metadata-3.9.1.jar
constituent[23]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-api-1.9.7.jar
constituent[24]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-connector-basic-1.9.7.jar
constituent[25]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-impl-1.9.7.jar
constituent[26]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-named-locks-1.9.7.jar
constituent[27]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-provider-3.9.1.jar
constituent[28]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-spi-1.9.7.jar
constituent[29]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-transport-file-1.9.7.jar
constituent[30]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-transport-http-1.9.7.jar
constituent[31]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-transport-wagon-1.9.7.jar
constituent[32]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-resolver-util-1.9.7.jar
constituent[33]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-settings-3.9.1.jar
constituent[34]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-settings-builder-3.9.1.jar
constituent[35]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-shared-utils-3.3.4.jar
constituent[36]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/maven-slf4j-provider-3.9.1.jar
constituent[37]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/org.eclipse.sisu.inject-0.3.5.jar
constituent[38]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/org.eclipse.sisu.plexus-0.3.5.jar
constituent[39]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/plexus-cipher-2.0.jar
constituent[40]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/plexus-component-annotations-2.1.0.jar
constituent[41]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/plexus-interpolation-1.26.jar
constituent[42]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/plexus-sec-dispatcher-2.0.jar
constituent[43]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/plexus-utils-3.5.1.jar
constituent[44]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/slf4j-api-1.7.36.jar
constituent[45]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/wagon-file-3.5.3.jar
constituent[46]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/wagon-http-3.5.3.jar
constituent[47]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/wagon-http-shared-3.5.3.jar
constituent[48]: file:/F:/environment/Maven/apache-maven-3.9.1/lib/wagon-provider-api-3.5.3.jar
---------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
        at javax.crypto.JceSecurity.loadPolicies(JceSecurity.java:378)
        at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:323)
        at javax.crypto.JceSecurity.access$000(JceSecurity.java:50)
        at javax.crypto.JceSecurity$1.run(JceSecurity.java:85)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:82)
        at javax.crypto.Cipher.getInstance(Cipher.java:518)
        at sun.security.ssl.JsseJce.getCipher(JsseJce.java:189)
        at sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
        at sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
        at sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:81)
        at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:67)
        at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:345)
        at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:46)
        at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:577)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.security.Provider$Service.getImplClass(Provider.java:1728)
        at java.security.Provider$Service.newInstance(Provider.java:1686)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
        at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:166)
        at org.eclipse.aether.transport.http.GlobalState.getConnectionManager(GlobalState.java:142)
        at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:62)
        at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:164)
        at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
        at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:93)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:128)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:170)
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:121)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:515)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:433)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:242)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:277)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:172)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:218)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1009)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:801)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:327)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:447)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:367)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:349)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:340)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:76)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:448)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:197)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.SecurityException: Framework jar verification can not be initialized
        at javax.crypto.JarVerifier.<clinit>(JarVerifier.java:236)
        ... 65 more
Caused by: java.security.PrivilegedActionException: java.security.cert.CertificateException: X.509 not found
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.crypto.JarVerifier.<clinit>(JarVerifier.java:194)
        ... 65 more
Caused by: java.security.cert.CertificateException: X.509 not found
        at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:188)
        at javax.crypto.JarVerifier$1.run(JarVerifier.java:200)
        at javax.crypto.JarVerifier$1.run(JarVerifier.java:195)
        ... 67 more
Caused by: java.security.NoSuchAlgorithmException: X.509 CertificateFactory not available
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:183)

**Comment by xiaozhangcc** [comment]
我也是啊，哥们你解决了吗
